### PR TITLE
Fixing the mvn based image build

### PR DESCRIPTION
**Pull request by k-wall**
Also switched to JDK 11 to match our current practice.

### CODE REVIEW

**Comment by k-wall** [comment]
(btw I'm planning to automate the maven releasse/image build in the same way we have for kas-fleetshard etc)

**Comment by shawkins** [comment]
> (btw I'm planning to automate the maven releasse/image build in the same way we have for kas-fleetshard etc)

Sounds good.  Do you plan to do the same for the java build artifacts?

**Review by shawkins — COMMENTED** [review]
LGTM

**Comment by k-wall** [comment]
> > (btw I'm planning to automate the maven releasse/image build in the same way we have for kas-fleetshard etc)
> 
> Sounds good. Do you plan to do the same for the java build artifacts?

Yes..

**Pull request merged**
